pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:chrome-ex/chrome-extension.git
          - cd chrome-extension.git
          - git push --mirror git@github.com:MihhailLastovski/chrome-extension.git